### ISSUE TITLE
Litecommerce forwards to the "purchased completed" page even if the user didn't pay.

### ISSUE THREAD

**Issue by liamzdenek** [litecommerce/core#5]
If I have an order and I'm paying with paypal, I hit submit. When the paypal page loads, i hit the back button, then re-submit the purchase button. Without redirecting me to paypal, Litecommerce thanks me for my order, and the administrative LC3 backend shows that an order has been placed.

I was able to reproduce this.

**Comment by maxmukhin** [comment]
Thank you for the discovering the issue. The problem has been already registered by the "developer" ticket - http://bt.litecommerce.com/view.php?id=40128  (just our testers and our team have access to it) 

Any way - thank you for your cooperation. We are working on this problem and inform you as soon as the issue is fixed

**Comment by maxmukhin** [comment]
This issue has been fixed in the current master-dev branch.

The fix will be available in the next 1.0.15 LC core version.
